### ISSUE TITLE
rangeBuilder and rnaturalearth fails to successfully call API

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#3]
In Lesson 4 ClimateProcessing there is an erroneous API call that will cause getDynamicAlphaHull() to fail. 

`hull <- rangeBuilder::getDynamicAlphaHull(x = alldfsp@coords, 
                             fraction = 1, # min. fraction of records we want included
                             partCount = 1, # number of polygons
                             initialAlpha = 20, # initial alpha size, 20m
                             clipToCoast = "terrestrial")
                            # proj = "+proj=longlat +datum=WGS84") # Appears that this is currently disfunctional.`

Will yield: 
```
Downloading a world basemap for clipping. This only needs to happen once.


trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_land.zip'
Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_land.zip'
In addition: Warning message:
In utils::download.file(file.path(address), zip_file <- tempfile()) :
  cannot open URL 'https://www.naturalearthdata.com/http/www.naturalearthdata.com/download/50m/physical/ne_50m_land.zip': HTTP status was '404 Not Found'
```

The failed call appears to be related to the missing '/' in 'https://www.naturalearthdata.com/http/www.naturalearthdata.com/download/50m/physical/ne_50m_land.zip' after the 'http/' as pointed out by Makenzi. 

Fix currenlty is to run 
`install.packages("rnaturalearth")`
As rnaturalearth seems to be the root of the erroneous call. This fix does not seem to be ubiquitous across systems however as it didnt resolve my errors until trying it at a later time (possibly calling the API too many times?). 
Possible reasons listed prior were firewalls by university internet (seems unlikely), Rversion, or Operating System. 

Fix has been tested on the cluster using versions 4.0 & 4.2 without errors. Will try on Windows operating system on non-university wifi at a later date.

**Comment by mgaynor1** [comment]
with the newest rangeBuilder update, everything seems good!

**Comment by mgaynor1** [comment]
@jtmiller28  Is this error now gone?

**Comment by jtmiller28** [comment]
Apologies for the stale issue, yes tested it yesterday as of 06/28/2023 and it seems with rangeBuilder v2.1 things are working correctly. Closing as complete.
