### ISSUE TITLE
installation of rangeBuilder *must* be through github

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#4]
^ Otherwise errors will occur leading you to multipolygon (sf) objects. To install 'correctly' use 
`remotes::install_github('ptitle/rangeBuilder')`
version should be 1.6 as of 02/20/2023,
2.0 is the Cran version and does not work with our current scripts.

**Comment by mgaynor1** [comment]
They updated the package in March! Wohoo
