### ISSUE TITLE
EcoSpat requires older versions 

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#5]
Issues exist on R version 4.2 for ecospat related to failing to download biomod2 dependent package correctly. 

Current fix: 
Use R version 4.1
`install.packages("biomod2")
install.packages("biospat") 
packageVersion("ecospat)`

Version should be '3.5'

**Comment by mgaynor1** [comment]
biospat is not avaliable on 4.2.1. But added biomod2 to the download
