### ISSUE TITLE
00_Setup has out of date packages 

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#6]
When fresh install is performed on packages, some packages will be newer than the listed version in setup.csv. Additionally, some packages are part of base R, therefore will fail any standard installation.

[Here](https://github.com/soltislab/BotanyENMWorkshops/files/11900640/update-list-output.csv) is a list of packages that are more up-to-date then currently the setup.csv suggests. 

R session info: 
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.0                         
year           2023                        
month          04                          
day            21                          
svn rev        84292                       
language       R                           
version.string R version 4.3.0 (2023-04-21)
nickname       Already Tomorrow

**Comment by mgaynor1** [comment]
Part 1: Remove base packages from setup.csv (these version = the R version you have installed):

- datasets, graphics, grDevices, methods, stats, utils

Part 2: Check and make sure the kuenm (1.1.9 to 1.1.10) and ecospat (3.5 to 3.5.1) do not break things and update.

Thanks for this catch JT!

**Comment by mgaynor1** [comment]
Updated but retained kuenm and ecospat to the old versions
