### ISSUE TITLE
RStoolbox is not available for standard installation on R version 4.3.0 

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#7]
```
install.packages("RStoolbox")
Installing package into ‘/home/jt-miller/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘RStoolbox’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

```
Looks like they haven't followed their CRAN updates: https://cran.r-project.org/web/packages/RStoolbox/index.html
Suggest to add it as a github_install along with rmaxent, kuenm, and gatoRs.
`library(devtools)
install_github("bleutner/RStoolbox")`

Rversion: 
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.0                         
year           2023                        
month          04                          
day            21                          
svn rev        84292                       
language       R                           
version.string R version 4.3.0 (2023-04-21)
nickname       Already Tomorrow

**Comment by mgaynor1** [comment]
JT will check if we still use it

**Comment by jtmiller28** [comment]
RSToolbox does not seem to be used. The only script that calls it in libraries is 07-ENM-Processing; however, I cannot find a function from within that package in the script, and the script appears to run without errors after removing it from load. I would suggest we can remove it from required packages and edit script 7.
