### ISSUE TITLE
05_PointBased: ecospat.grid.clim.dyn suggests there are not enough relocations available.

### ISSUE THREAD

**Issue by jtmiller28** [soltislab/BotanyENMWorkshops#8]
The code chunk: 
### create occurrence density grids based on the ordination data
z1 <- ecospat.grid.clim.dyn(scores.clim, scores.clim, p1.score, R = 100)
z2 <- ecospat.grid.clim.dyn(scores.clim, scores.clim, p2.score, R = 100)
z3 <- ecospat.grid.clim.dyn(scores.clim, scores.clim, p3.score, R = 100)
z4 <- ecospat.grid.clim.dyn(scores.clim, scores.clim, p4.score, R = 100)
zlist  <- list(z1, z2, z3, z4)

Currently will error out: Error in adehabitatHR::kernelUD(sp::SpatialPoints(xr[, 1:2]), h = "href",  : 
  At least 5 relocations are required to fit an home range

scores.clim are built off the PCAs per species, there seems to be adequate sample size for relocation. Unsure whats actually happening here. 

Note: My ecospat version is 3.5.1

**Comment by ewhite344** [comment]
Hey JT! I'm not an expert on the ecospat package but I can try to help-- the code worked for me (so I'm not sure if y'all already resolved this issue)-- but I also know the R spatial packages can be really finicky. Does your scores.clim dataframe also have 2060 observations? I'm wondering if this might actually an issue somewhere earlier in the code that's just causing problems here.

**Comment by jtmiller28** [comment]
Apologies for the late response! 

It was definitely a me thing, don't mess with your lapack library it causes issues with PCAs. Closing this issue as complete.
